#!/usr/bin/env ruby

# set up bundler
require "rubygems"
require "bundler/setup"

# pry is our repl
require "pry"

require "./lib/listlace"

Listlace::Database.connect
Listlace::Database.generate_schema unless Listlace::Database.exists?

puts "Hello, you have #{Listlace::Track.count} songs."

Listlace.pry quiet: true, prompt: Listlace::PROMPT
