#!/usr/bin/env ruby
require "./lib/listlace"
require "pry"

Listlace.connect
Listlace.generate_schema unless File.exists?("db/library.sqlite3")

puts "Hello, you have #{Listlace::Track.count} songs."

Listlace.pry quiet: true, prompt: Listlace::PROMPT
