#!/usr/bin/env ruby

# set up bundler
require "rubygems"
require "bundler/setup"
require "pry"

require "./lib/listlace"

Listlace.connect
Listlace.generate_schema unless File.exists?("db/library.sqlite3")

puts "Hello, you have #{Listlace::Track.count} songs."

Listlace.pry quiet: true, prompt: Listlace::PROMPT
